# FROM python:3.11
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Set environment variables
ENV PYTHON_VERSION 3.10
ENV DEBIAN_FRONTEND=noninteractive

# Install basic utilities (these rarely change, so it will be cached)
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common && \
    add-apt-repository ppa:freecad-maintainers/freecad-stable && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    ccache \
    cmake \
    curl \
    git \
    pkg-config \
    ssh \
    sudo \
    unzip \
    wget \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    libjpeg-dev \
    libpng-dev \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libffi-dev \
    libsqlite3-dev \
    libbz2-dev \
    ffmpeg \
    python3-tk \
    liblzma-dev \
    ninja-build \
    libosmesa6-dev \
    libboost-all-dev \
    freecad \
    potrace \
    xvfb \
    libncurses5-dev \
    libncursesw5-dev \
    libreadline-dev \
    libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apk/*

# Set symlink for python3
RUN ln -s /usr/bin/python3 /usr/bin/python

# create a user, since we don't want to run as root
RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

# Install pyenv (cache this layer if the Python version doesn't change)
ENV PYENV_ROOT /home/jovyan/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN curl https://pyenv.run | bash && \
    pyenv update && \
    pyenv install $PYTHON_VERSION && \
    pyenv global $PYTHON_VERSION && \
    pyenv rehash

# Install poetry
RUN pip install \
    poetry \
    nuitka \
    wheel \
    setuptools \
    jupyterhub==4.* \
    notebook==7.*

CMD ["jupyterhub-singleuser"]